<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\TradingWeek;
use App\Models\WeekPerformanceDetail;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use PhpOffice\PhpSpreadsheet\IOFactory;
use PhpOffice\PhpSpreadsheet\Shared\Date;
use Carbon\Carbon;

class TradingWeekController extends Controller
{
    /**
     * Display a listing of the resource.
     */
    public function index()
    {
        $weeks = TradingWeek::orderBy('display_order')
            ->orderBy('start_date', 'desc')
            ->with('performanceDetail')
            ->get();
        
        return view('admin.pages.trading-weeks.index', compact('weeks'));
    }

    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        return view('admin.pages.trading-weeks.create');
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        $validated = $request->validate([
            'week_label' => 'nullable|string|max:255',
            'start_date' => 'required|date',
            'end_date' => 'required|date|after_or_equal:start_date',
            'total_gain' => 'required|numeric',
            'account_size' => 'required|numeric|min:0',
            'week_type' => 'required|in:normal,current,last',
            'display_order' => 'nullable|integer|min:0',
            'is_active' => 'nullable|boolean',
            
            // Performance Details
            'trade_accuracy' => 'nullable|numeric|min:0|max:100',
            'risk_reward_ratio' => 'nullable|numeric|min:0',
            'largest_drawdown' => 'nullable|numeric',
            'chart_labels' => 'nullable|string',
            'chart_data' => 'nullable|string',
            'daily_performance' => 'nullable|string',
            'markets_traded' => 'nullable|string',
        ]);

        try {
            DB::beginTransaction();

            // Prepare week data
            $weekData = [
                'start_date' => $validated['start_date'],
                'end_date' => $validated['end_date'],
                'total_gain' => $validated['total_gain'],
                'account_size' => $validated['account_size'],
                'week_type' => $validated['week_type'],
                'display_order' => $validated['display_order'] ?? 0,
                'is_active' => $request->has('is_active'),
            ];

            // Create week (week_label will be auto-generated by model)
            $week = TradingWeek::create($weekData);

            DB::commit();

            return redirect()->route('admin.trading-weeks.index')
                ->with('success', 'Trading week created successfully!');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()
                ->withInput()
                ->with('error', 'Error creating trading week: ' . $e->getMessage());
        }
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $week = TradingWeek::with('performanceDetail')->findOrFail($id);
        return view('admin.pages.trading-weeks.show', compact('week'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        $week = TradingWeek::with('performanceDetail')->findOrFail($id);
        return view('admin.pages.trading-weeks.edit', compact('week'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        $week = TradingWeek::findOrFail($id);

        $validated = $request->validate([
            'week_label' => 'nullable|string|max:255',
            'start_date' => 'required|date',
            'end_date' => 'required|date|after_or_equal:start_date',
            'total_gain' => 'required|numeric',
            'account_size' => 'required|numeric|min:0',
            'week_type' => 'required|in:normal,current,last',
            'display_order' => 'nullable|integer|min:0',
            'is_active' => 'nullable|boolean',
        ]);

        try {
            DB::beginTransaction();

            // Update week data
            $week->update([
                'start_date' => $validated['start_date'],
                'end_date' => $validated['end_date'],
                'total_gain' => $validated['total_gain'],
                'account_size' => $validated['account_size'],
                'week_type' => $validated['week_type'],
                'display_order' => $validated['display_order'] ?? $week->display_order,
                'is_active' => $request->has('is_active'),
            ]);

            // Update total_gain in performance detail if exists
            if ($week->performanceDetail) {
                $week->performanceDetail->update(['total_gain' => $validated['total_gain']]);
            }

            DB::commit();

            return redirect()->route('admin.trading-weeks.index')
                ->with('success', 'Trading week updated successfully!');
        } catch (\Exception $e) {
            DB::rollBack();
            return redirect()->back()
                ->withInput()
                ->with('error', 'Error updating trading week: ' . $e->getMessage());
        }
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        try {
            $week = TradingWeek::findOrFail($id);
            $week->delete(); // Performance detail will be deleted via cascade

            return redirect()->route('admin.trading-weeks.index')
                ->with('success', 'Trading week deleted successfully!');
        } catch (\Exception $e) {
            return redirect()->route('admin.trading-weeks.index')
                ->with('error', 'Error deleting trading week: ' . $e->getMessage());
        }
    }

    /**
     * Import weeks from Excel/CSV
     */
    public function import(Request $request)
    {
        $request->validate([
            'excel_file' => [
                'required',
                'file',
                'max:10240', // 10MB
                // Accept common spreadsheet and CSV MIME types (some browsers send text/plain)
                'mimetypes:text/plain,text/csv,text/comma-separated-values,application/csv,application/vnd.ms-excel,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            ],
        ]);

        $file = $request->file('excel_file');
        $extension = strtolower($file->getClientOriginalExtension());

        $errors = [];
        $successCount = 0;

        try {
            DB::beginTransaction();

            if ($extension === 'csv') {
                list($successCount, $errors) = $this->importCsv($file);
            } else {
                list($successCount, $errors) = $this->importExcel($file);
            }

            DB::commit();

            $message = "Successfully imported {$successCount} week(s).";
            if (!empty($errors)) {
                $message .= " Errors: " . implode('; ', array_slice($errors, 0, 5));
                if (count($errors) > 5) {
                    $message .= " and " . (count($errors) - 5) . " more.";
                }
            }

            return redirect()->route('admin.trading-weeks.index')
                ->with($successCount > 0 ? 'success' : 'error', $message);
        } catch (\Exception $e) {
            DB::rollBack();
            \Log::error('Trading Week Import Error: ' . $e->getMessage(), [
                'file' => $file->getClientOriginalName(),
                'trace' => $e->getTraceAsString()
            ]);
            return redirect()->route('admin.trading-weeks.index')
                ->with('error', 'Error importing file: ' . $e->getMessage() . ' (Line: ' . $e->getLine() . ')');
        }
    }

    /**
     * Import CSV file
     * Returns: [successCount, errors]
     */
    private function importCsv($file)
    {
        $handle = fopen($file->getRealPath(), 'r');
        if (!$handle) {
            throw new \Exception('Unable to read CSV file.');
        }

        $errors = [];
        $successCount = 0;
        $rowNumber = 1; // Start from 1 (header is row 0)

        // Skip header
        fgetcsv($handle);
        $rowNumber++;

        while (($row = fgetcsv($handle)) !== false) {
            if (count($row) < 5) {
                $errors[] = "Row {$rowNumber}: Insufficient columns (need at least 5)";
                $rowNumber++;
                continue;
            }

            try {
                $this->createWeekFromRow($row);
                $successCount++;
            } catch (\Exception $e) {
                $errors[] = "Row {$rowNumber}: " . $e->getMessage();
            }
            $rowNumber++;
        }

        fclose($handle);

        return [$successCount, $errors];
    }

    /**
     * Import Excel file
     * Returns: [successCount, errors]
     */
    private function importExcel($file)
    {
        $spreadsheet = IOFactory::load($file->getRealPath());
        $sheet = $spreadsheet->getActiveSheet();
        $rows = $sheet->toArray(null, true, true, true);

        $errors = [];
        $successCount = 0;
        $rowNumber = 1; // Start from 1 (header is row 0)

        // Remove header
        array_shift($rows);
        $rowNumber++;

        foreach ($rows as $row) {
            $rowValues = array_values($row);
            if (count($rowValues) < 5) {
                $errors[] = "Row {$rowNumber}: Insufficient columns (need at least 5)";
                $rowNumber++;
                continue;
            }

            try {
                $this->createWeekFromRow($rowValues);
                $successCount++;
            } catch (\Exception $e) {
                $errors[] = "Row {$rowNumber}: " . $e->getMessage();
            }
            $rowNumber++;
        }

        return [$successCount, $errors];
    }

    /**
     * Create week + performance from array row
     * Expected columns:
     * 0: week_type (normal/current/last)
     * 1: start_date (Y-m-d)
     * 2: end_date (Y-m-d)
     * 3: total_gain
     * 4: account_size
     * 5: trade_accuracy
     * 6: risk_reward_ratio
     * 7: largest_drawdown
     * 8: chart_labels (comma separated)
     * 9: chart_data (comma separated numbers)
     * 10-12: Monday Day, Monday Change, Monday Equity
     * 13-15: Tuesday Day, Tuesday Change, Tuesday Equity
     * 16-18: Wednesday Day, Wednesday Change, Wednesday Equity
     * 19-21: Thursday Day, Thursday Change, Thursday Equity
     * 22-24: Friday Day, Friday Change, Friday Equity
     * 25-26: Market 1, Volume 1
     * 27-28: Market 2, Volume 2
     * 29-30: Market 3, Volume 3
     * 31: display_order (optional)
     * 32: is_active (1/0 optional)
     */
    private function createWeekFromRow(array $row)
    {
        // Ensure minimum columns to avoid undefined offsets
        $row = array_pad($row, 33, null);

        $weekType = strtolower(trim($row[0] ?? 'normal'));
        if (!in_array($weekType, ['normal', 'current', 'last'])) {
            $weekType = 'normal';
        }

        $weekData = [
            'week_type' => $weekType,
            'start_date' => $this->normalizeDate($row[1] ?? null),
            'end_date' => $this->normalizeDate($row[2] ?? null),
            'total_gain' => $this->cleanNumber($row[3] ?? 0),
            'account_size' => $this->cleanNumber($row[4] ?? 0),
            'display_order' => isset($row[31]) ? intval($row[31]) : 0,
            'is_active' => isset($row[32]) ? (bool) $row[32] : true,
        ];

        // Basic validation
        if (empty($weekData['start_date']) || empty($weekData['end_date'])) {
            throw new \Exception('Start date or End date is missing or invalid. Start: ' . ($row[1] ?? 'empty') . ', End: ' . ($row[2] ?? 'empty'));
        }

        try {
            $week = TradingWeek::create($weekData);
        } catch (\Exception $e) {
            throw new \Exception('Failed to create week: ' . $e->getMessage() . ' | Data: ' . json_encode($weekData));
        }

        $performanceData = [
            'trading_week_id' => $week->id,
            'total_gain' => $weekData['total_gain'],
            'trade_accuracy' => $this->cleanNumber($row[5] ?? null),
            'risk_reward_ratio' => $this->cleanNumber($row[6] ?? null),
            'largest_drawdown' => $this->cleanNumber($row[7] ?? null),
        ];

        // Chart labels/data
        if (!empty($row[8])) {
            $performanceData['chart_labels'] = $this->parseCommaSeparated($row[8]);
        }
        if (!empty($row[9])) {
            $performanceData['chart_data'] = $this->parseCommaSeparatedNumbers($row[9]);
        }

        // Daily performance from separate columns
        $dailyPerformance = [];
        $days = ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday'];
        $dayIndex = 10;
        
        foreach ($days as $day) {
            $dayName = trim($row[$dayIndex] ?? $day);
            $change = trim($row[$dayIndex + 1] ?? '');
            $equity = trim($row[$dayIndex + 2] ?? '');
            
            if (!empty($change) || !empty($equity)) {
                $dailyPerformance[] = [
                    'day' => $dayName,
                    'change' => $change,
                    'equity' => $equity,
                ];
            }
            $dayIndex += 3;
        }
        
        if (!empty($dailyPerformance)) {
            $performanceData['daily_performance'] = $dailyPerformance;
        }

        // Markets traded from separate columns
        // After 10 basic columns + 15 daily columns (5 days × 3) = column 25
        $marketsTraded = [];
        $marketIndex = 25;
        
        for ($i = 1; $i <= 3; $i++) {
            $market = trim($row[$marketIndex] ?? '');
            $volume = isset($row[$marketIndex + 1]) ? $this->cleanNumber($row[$marketIndex + 1]) : 0;
            
            if (!empty($market) && $volume > 0) {
                $marketsTraded[] = [
                    'market' => $market,
                    'volume_percentage' => $volume,
                ];
            }
            $marketIndex += 2;
        }
        
        if (!empty($marketsTraded)) {
            $performanceData['markets_traded'] = $marketsTraded;
        }

        try {
            WeekPerformanceDetail::create($performanceData);
        } catch (\Exception $e) {
            // If performance detail creation fails, delete the week to maintain consistency
            if (isset($week)) {
                $week->delete();
            }
            throw new \Exception('Failed to create performance detail: ' . $e->getMessage());
        }
    }

    /**
     * Normalize dates from CSV/Excel (handles Excel numeric dates too)
     */
    private function normalizeDate($value): ?string
    {
        if ($value === null || $value === '') {
            return null;
        }

        // Excel numeric date
        if (is_numeric($value)) {
            try {
                return Date::excelToDateTimeObject($value)->format('Y-m-d');
            } catch (\Exception $e) {
                // If it's a numeric string but not Excel date, continue to string parsing
            }
        }

        // String date
        try {
            $trimmed = trim((string)$value);
            
            // Try common formats explicitly (order matters - try most specific first)
            $formats = [
                'Y-m-d',           // 2025-11-24
                'm/d/Y',           // 11/24/2025 (US format)
                'M/d/Y',           // 11/24/2025 (with leading zero)
                'n/j/Y',           // 11/24/2025 (without leading zero)
                'd/m/Y',           // 24/11/2025 (European format)
                'd-m-Y',           // 24-11-2025
                'm-d-Y',           // 11-24-2025
                'Y/m/d',           // 2025/11/24
                'M j, Y',          // Nov 24, 2025
                'F j, Y',          // November 24, 2025
            ];
            
            foreach ($formats as $fmt) {
                try {
                    $parsed = Carbon::createFromFormat($fmt, $trimmed);
                    if ($parsed) {
                        return $parsed->format('Y-m-d');
                    }
                } catch (\Exception $e) {
                    continue;
                }
            }
            
            // Fallback to Carbon::parse (more flexible but less strict)
            try {
                $parsed = Carbon::parse($trimmed);
                return $parsed->format('Y-m-d');
            } catch (\Exception $e) {
                \Log::warning('Date normalization failed', [
                    'value' => $value,
                    'trimmed' => $trimmed,
                    'error' => $e->getMessage()
                ]);
                return null;
            }
        } catch (\Exception $e) {
            \Log::warning('Date normalization error', [
                'value' => $value,
                'error' => $e->getMessage()
            ]);
            return null;
        }
    }

    /**
     * Parse comma-separated string into array
     */
    private function parseCommaSeparated($string)
    {
        if (empty($string)) {
            return [];
        }
        return array_map('trim', explode(',', $string));
    }

    /**
     * Parse comma-separated numbers into array
     */
    private function parseCommaSeparatedNumbers($string)
    {
        if (empty($string)) {
            return [];
        }
        $numbers = array_map('trim', explode(',', $string));
        return array_map(function ($n) {
            return $this->cleanNumber($n);
        }, $numbers);
    }

    /**
     * Parse JSON string or return as array
     */
    private function parseJsonField($string)
    {
        if (empty($string)) {
            return [];
        }
        
        // Try to decode as JSON first
        $decoded = json_decode($string, true);
        if (json_last_error() === JSON_ERROR_NONE) {
            return $decoded;
        }
        
        // If not valid JSON, return empty array
        return [];
    }

    /**
     * Clean numeric strings (remove commas, $, %, spaces) and return float or null
     */
    private function cleanNumber($value): ?float
    {
        if ($value === null || $value === '') {
            return null;
        }

        if (is_numeric($value)) {
            return floatval($value);
        }

        $cleaned = str_replace([',', '%', '$', ' '], '', $value);
        if (is_numeric($cleaned)) {
            return floatval($cleaned);
        }

        return null;
    }
}
